### ISSUE TITLE
Question : XAML extensions, whats possible ?!

### ISSUE THREAD

**Issue by liquidboy** [Microsoft/App-Extensibility-Sample#1]
Hi,

Thanks for this demo ... I've been trying to understand the limitations of extensions in its current state ..
From what I can gather it seems like its optimized for "web extensions"  and not "XAML extensions"...

Is it possible to have XAML components defined in the extension , eg. a usercontrol.xaml & usercontrol.cs  and have that used in the host ?

I want to be able to have extensions have XAML UI & Code and then the host render those UI's/Code ..

p.s. I can see how this is done with web UI's because we are sending across html/css/js and using the webview to render/eval those bits ...

**Comment by nitewulf** [comment]
What he said!!!!!

I was just about to post this EXACT same question.

I got super excited when I watched the Extensibility presentation from Build 2016 on channel 9 yesterday.  I downloaded the demo and began to tinker.  I added a ClassLibrary project to the RotateExtension Solution which contains a "Hello World" xaml UserControl.  Then I added it as a reference to the RotateExtension Project and modified the Post Build command to drop the .dll into the Public folder.  I was SO excited I was going to be able to grab ClassLibrary.dll from the ExtensionManager in the ExtensibilitySample instead of loading the extension.html.... or so I thought.

Reflection is so handicapped in UWP.  Why can't I load this .dll?  

This seems like a perfectly safe method of using dynamic code.  The dymanic .dlls will be provided by a trusted signed .appX and made available to the host application through the extensions public folder.

C'mon you've got a good framework here.  Lets make it better.

**Comment by dkbennett** [comment]
Thank you for the feedback on this, we understand the frustration. We are looking at making improvements in this area.

Presently, App Extensions don't support binaries like dropping libraries and loading them. The UWP Load Library search does not allow you to specify a path, and it doesn't include known extension folders in its dll search. It's not supported by-design because it breaks package isolation and trust. While the source is a signed package, that library could still break your app when loaded, which would make loading extensions risky for the user. The extension model is either out of proc via app service / packaged COM, or hosted script.

There are several ways to work with the existing model:

1) Use App Services for any code you need to run. This doesn't help you embed, but it works well for cross-app experiences where you want private data and execution on one app to plug into an extension experience in another app.

2) If your app is a Desktop Bridge app it can load extensions installed by non-UWPs, such as supporting a legacy plugin system. There are no load library restrictions for Desktop Bridge apps.

3) If your app and your extensions are both Desktop Bridge apps, you can use Out-of-proc Packaged COM to communicate. 

4) Use a hosted scripting language for your extension model. You can use html/Javascript along with the Chakra engine (which is the same engine Edge uses). Python and Lua also have UWP samples too.
[https://github.com/Microsoft/Chakra-Samples](https://github.com/Microsoft/Chakra-Samples)
[https://github.com/ms-iot/python](https://github.com/ms-iot/python)
[https://github.com/XamlBrewer/UWP-Lua-Scripting-Sample](https://github.com/XamlBrewer/UWP-Lua-Scripting-Sample)

**Comment by moderndev** [comment]
Thanks BUT I want to use binaries in an extension and not a round about way ..  

If desktop bridge can get around this isolation trust you speak of then a pure UWP app using UWP extensions with binaries should also be allowed. 

Otherwise it sounds like a double standard not allowing UWP apps what Desktop Bridge apps are allowed!

**Comment by dkbennett** [comment]
It would be helpful to us to get more information on what you are trying to do. Please describe the scenario you are trying to enable and why the hosted or out-of-proc options do not work for you. This is beneficial for our future planning on this feature. Are you trying to make an extension platform for third parties to enhance your app, or extensions for your own use to release (like a feature-pack or expansion)?

**Comment by iurifarenzena** [comment]
I've managed to create a **modular** UWP app, being able to deploy it with only certain features.
The application is able to load and render XAML usercontrols with their classes and dependencies from _"not referenced assemblies"_, and it works.

There are three problems in my approach:

- There's no way to add more features after deploy. A custom appx installation is necessary for each feature/module set.
- I've only managed to create custom appx using de _**Debug**_ build configuration.
- It's a pain in the _neck_ to implement it

I'm thinking about creating a tutorial to show how to achieve that, but it would take a lot of time. Let me know if this is an interesting approach for what you want.

@dkbennett could you help me on creating a appx using the _**Release**_ build configuration?

**Comment by dkbennett** [comment]
@iurifarenzena   I'm interested in what you are doing here, do you have a GitHub link for your project I can view?

Also, what scenario are you trying to enable with a modular UWP?

**Comment by iurifarenzena** [comment]
@dkbennett Unfortunately it's a private enterprise application, so I can't share it's code, but I'll try to reproduce that in a shareable and functional way.

About the scenario, the UWP application is part of a production measurement system, being responsible for data collection from the shop floor. We've chosen UWP because of Raspberry PI, and a modular app is important for us cause some costumer may want different features like: custom chart visualisation available for machine operators; live view from each workstation through web-cam; or a custom form to access company's ERP system's data.

About the custom appx, I've created a modified _package.map.txt_ file including the assemblies that are not available as default (not referenced in the project), and used it with the _makeappx_ and _signtool_ utilities. It works for the _**Debug**_ build configuration because it's "all about" copying assemblies to the app installation folder. But I haven't figured out yet how to do that for the _**Release**_ because UWP seems to compile everything into a single dll, and that prevents the additional assemblies from being loaded at run time.

PS: sorry for the long post. I don't know how to be more succinct cause there is a lot of details.

**Comment by dkbennett** [comment]
@iurifarenzena Are your customers creating plugins for your UWP app, or are you providing the modules they need, depending on their needs? Our AppExtensions are designed for the former, where 3rd parties create the extensions/plugins and your app hosts them.  If you are trying to create a multi-package App with different sets of packages this would not be the best option for you. 

I will send you an email to discuss further.

**Comment by iurifarenzena** [comment]
@dkbennett For my design I'm creating the modules and giving different sets to the customer. Some are standard modules, and some are exclusive for a given customer.

**Comment by moderndev** [comment]
In our case its a private enterprise UWP XAML C# app we are investigating of creating ..  Its a large application (Shell - which is the extension host) that will be made up of several modules (messages, forms, security, packages, 2D viewer, bim etc) ...  Each of these modules can be purchased separately by the user and each module has UI/Views/Models that it needs to load within the main "Shell" application ...  

Each module should be an "extension" that the user should be able to download from the store and when they install it in the "shell" application (extension host) it will light up that feature/module.

This UWP native app will mirror our current Web application that is also a module based product that users pay per module..   

p.s. before you answer "AppExtensions wasn't designed for this" ....  my rebuttal is, why isn't it ... All we are asking for is for "extensions" to be allowed to load XAML and code (views/models) inside the host application..  Even if that means keeping the extension running in its own process and letting it render it's UI within a Host surface !!

**Comment by dkbennett** [comment]
@moderndev  AppExtensions weren't designed for what you want...but Optional Packages were! :)

AppExtensions are intended for 3rd parties to extend your app, and what you are looking for is first party extension. There's a big trust difference between those two scenarios, so we have different solutions. We allow a lot more to occur with first party extensions or modules, which we call Optional Packages.

Optional Packages offer you a way to modularize your app so it can be extended through additional packages. Those packages are tightly bound to the app and version for which they were designed, but they allow you to load code in-proc as if it were part of your original main package. We treat them as if they are part of your main package, and they cannot run on their own.

For more information, please see this recent blog post:
https://blogs.msdn.microsoft.com/appinstaller/2017/04/05/uwpoptionalpackages/

AppExtensions are intended for more App-to-App plugin-style scenarios between third parties. This is why we do not allow in-proc running of code with App Extensions, nor offer cross-package dependencies.

**Comment by liquidboy** [comment]
thankyou for this @dkbennett  this sounds exactly like what im asking for feature wise ... Ill devote time this week to play with optional packages!!   Feel free to close this as answered with the above answer!

**Comment by moderndev** [comment]
Hi  @dkbennett, I just noticed that optional packages "cannot be managed code in the current release and has to be native code due to a .Net limitation"   ..  Could you shed more light as to what limitations in .Net is causing this? So that we can direct attention to it to the relevant .NET teams ?!

**Comment by dkbennett** [comment]
@moderndev I would recommend asking that in the comments of the blog post; there's likely a lot of other folks interested in that answer and it would be good to have it close to the blog itself.

I'm going to mark this as closed per liquidboy's feedback, and it seems the Optional Package feature addresses the need in which the folks in this thread are interested.
